### PR TITLE
update requests for urllib3 version disagreement

### PR DESCRIPTION
**Pull request by jrgm**
When started in stage with the `server` entrypoint, the tokenserver fails to start up with
```
{"error": "ContextualVersionConflict(urllib3 1.25.2 (/usr/local/lib/python2.7/site-packages), Requirement.parse('urllib3<1.25,>=1.21.1'), set(['requests']))", "traceback": "Uncaught exception:
  File \"/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py\", line 583, in spawn_worker
    worker.init_process()
  File \"/usr/local/lib/python2.7/site-packages/gunicorn/workers/ggevent.py\", line 203, in init_process
    super(GeventWorker, self).init_process()
  File \"/usr/local/lib/python2.7/site-packages/gunicorn/workers/base.py\", line 129, in init_process
    self.load_wsgi()
  File \"/usr/local/lib/python2.7/site-packages/gunicorn/workers/base.py\", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File \"/usr/local/lib/python2.7/site-packages/gunicorn/app/base.py\", line 67, in wsgi
    self.callable = self.load()
  File \"/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py\", line 50, in load
    return self.load_pasteapp()
  File \"/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py\", line 46, in load_pasteapp
    return load_pasteapp(self.cfgurl, self.relpath, global_conf=self.cfg.paste_global_conf)
  File \"/usr/local/lib/python2.7/site-packages/gunicorn/app/pasterapp.py\", line 71, in load_pasteapp
    global_conf=global_conf)
  File \"/usr/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py\", line 253, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File \"/usr/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py\", line 277, in loadobj
    global_conf=global_conf)
  File \"/usr/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py\", line 302, in loadcontext
    global_conf=global_conf)
  File \"/usr/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py\", line 326, in _loadconfig
    return loader.get_context(object_type, name, global_conf)
  File \"/usr/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py\", line 455, in get_context
    global_additions=global_additions)
  File \"/usr/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py\", line 564, in _pipeline_app_context
    APP, pipeline[-1], global_conf)
  File \"/usr/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py\", line 459, in get_context
    section)
  File \"/usr/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py\", line 481, in _context_from_use
    object_type, name=use, global_conf=global_conf)
  File \"/usr/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py\", line 412, in get_context
    global_conf=global_conf)
  File \"/usr/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py\", line 302, in loadcontext
    global_conf=global_conf)
  File \"/usr/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py\", line 334, in _loadegg
    return loader.get_context(object_type, name, global_conf)
  File \"/usr/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py\", line 625, in get_context
    object_type, name=name)
  File \"/usr/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py\", line 645, in find_egg_entry_point
    pkg_resources.require(self.spec)
  File \"/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py\", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File \"/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py\", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
<class 'pkg_resources.ContextualVersionConflict'>
ContextualVersionConflict(urllib3 1.25.2 (/usr/local/lib/python2.7/site-packages), Requirement.parse('urllib3<1.25,>=1.21.1'), set(['requests']))
", "time": "2019-10-25T21:39:03.997360Z", "v": 1, "message": "Exception in worker process", "hostname": "ip-172-31-29-111.ec2.internal", "pid": 14, "op": "gunicorn.error", "name": "gunicorn.error"}
```

I "fix" it here by bumping the `requests` version, c.f. https://github.com/psf/requests/pull/5092 and https://github.com/psf/requests/issues/5067, but ¯\_(ツ)_/¯

### CODE REVIEW

**Comment by jrgm** [comment]
PR targeted at release-1.4.4, but maybe I should have done it against master. This will need another tag, but I'll work with this `dockerpush` tag for now.

**Comment by rfk** [comment]
> PR targeted at release-1.4.4, but maybe I should have done it against master. 

I'm going to just redirect to master for simplicity, since no other code changes have landed.

**Comment by rfk** [comment]
> Merging is blocked
> The base branch requires all commits to be signed. Learn more about signing commits. 

Ugh. @jrgm I guess you don't have commit signing set up, but I can make a fresh PR with a signed commit for merge.

**Comment by jrgm** [comment]
I do have commit signing set up, but I guess not on this repository. I'll fix that and put up another PR.

**Comment by jrgm** [comment]
closing in favour of https://github.com/mozilla-services/tokenserver/pull/152

**Pull request closed without merging**
