### PR TITLE
provide `python` target on entrypoint for workers

### PR DESCRIPTION
**Pull request by jrgm**
The worker tasks start with a python command line like "python -m tokenserver.scripts.process_account_events -v ./settings.ini ts-account-change-stage". So `docker-entrypoint.sh` needs a case to handle and exec that command.

(Something about this doesn't reallly feel right, though).

### CODE REVIEW

**Comment by jrgm** [comment]
> Looks fine, but we could also override ENTRYPOINT I guess?

Yeah. I considered that but I don't see with Puppet docker::run to override entrypoint.

**Comment by jrgm** [comment]
Oops. I really shouldn't have merged this for this repo, but my brain was on autopilot.

**Comment by jrgm** [comment]
Say @rfk - can you prep a 1.4.2 that includes this change?

**Comment by rfk** [comment]
Yep: https://github.com/mozilla-services/tokenserver/releases/tag/1.4.2

Enjoy!

**Pull request merged**
